### ISSUE TITLE
SECURITY ALERT: Leaked Credentials in `.env` and `.env.production`

### ISSUE THREAD

**Issue by sabeerbikba** [shemaikuzwe/urban-deals-shop#5]
It's been observed that credentials are present in the `.env` and `.env.production` files. For better security and to prevent accidental exposure of sensitive information, it's recommended to use environment variables provided by Vercel.

**Recommendation:**

Please refer to the [Vercel Environment Variables Documentation](https://vercel.com/docs/projects/environment-variables) to properly configure and manage environment variables for your project.

**Action Required:**

1. Remove sensitive credentials from the `.env` and `.env.production` files.
2. Configure environment variables using Vercel's environment variable management.

**Additional Notes:**

Ensure that these changes are tested to confirm that the application behaves as expected after removing the credentials.

**Comment by ikuzweelisa** [comment]
Removed sensitive credentials from the .env and .env.production
